# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ios-moe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ios-moe
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'
end

target 'ios-moe-Test' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ios-moe-Test

end
